#
# Config File for the Flexible Determinist keyboard
#
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  standoff: 2.5
  $default_width: cx
  $default_height: cy

points:
  rotate: -20
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      rows:
        bottom:
          row_net: D10
          mirror.row_net: A1
        middle:
          row_net: D6
          mirror.row_net: D24
        top:
          row_net: D5
          mirror.row_net: D25
      columns:
        pinkie:
          key:
            column_net: A2
            splay: 10
        ring:
          key:
            column_net: A3
            stagger: 12
            splay: -6
            spread: kx+2
        middle:
          key:
            column_net: D11
            stagger: 8
            splay: -4
            spread: kx+2
        index:
          key:
            column_net: D12
            stagger: -8
            spread: kx
        inner:
          key:
            column_net: D9
            stagger: -4
            spread: kx
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_middle_bottom
        shift: [14, -32]
      rows:
        cluster:
          row_net: D13
          mirror.row_net: A0
      columns:
        outer:
          key.column_net: D11
        mod:
          key:
            column_net: D12
            splay: -15
            spread: kx+1.5
            shift: [2, -2.25]
        space:
          key:
            column_net: D9
            splay: -10
            spread: kx+1.5
            shift: [3, 1]
            height: 1.5kx
  mirror: &mirror
    ref: matrix_inner_top
    distance: 2.1kx

outlines:
  # format: svg
  raw:
    - what: rectangle
      where: true
      size: [px, py]
      expand: 2
      bound: true
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        - ref: matrix_pinkie_top
          shift: [-0.6px, 0.6py]
        - ref: matrix_pinkie_top
          shift: [0.48px, 0.6py]
        - ref: matrix_ring_top
          shift: [-0.6px, 0.6py]
        - ref: matrix_ring_top
          shift: [0.43px, 0.6py]
        - ref: matrix_middle_top
          shift: [-0.6px, 0.6py]
        - ref: matrix_middle_top
          shift: [0.56px, 0.6py]
        - ref: matrix_index_top
          shift: [-0.25px, 0.6py]

# center point
        - ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, 0.6py]

# mirror
        - ref: mirror_matrix_index_top
          shift: [-0.25px, 0.6py]
        - ref: mirror_matrix_middle_top
          shift: [0.56px, 0.6py]
        - ref: mirror_matrix_middle_top
          shift: [-0.6px, 0.56py]
        - ref: mirror_matrix_ring_top
          shift: [0.43px, 0.6py]
        - ref: mirror_matrix_ring_top
          shift: [-0.6px, 0.6py]
        - ref: mirror_matrix_pinkie_top
          shift: [0.48px, 0.6py]
        - ref: mirror_matrix_pinkie_top
          shift: [-0.6px, 0.6py]

# end top line
        - ref: mirror_matrix_pinkie_bottom
          shift: [-0.6px, -0.6py]
        - ref: mirror_matrix_pinkie_bottom
          shift: [0.6px, -0.6py]

        - ref: mirror_matrix_ring_bottom
          shift: [-0.22px, -0.6py]
        - ref: mirror_matrix_ring_bottom
          shift: [0.8px, -0.6py]

        - ref: mirror_thumb_outer_cluster
          shift: [-0.6px, -0.6py]
        - ref: mirror_thumb_space_cluster
          shift: [0.6px, -0.55py]

  # bottom center
        - ref.aggregate.parts: [thumb_space_cluster, mirror_thumb_space_cluster]
          shift: [0, 0]

        - ref: thumb_space_cluster
          shift: [0.6px, -0.55py]
        - ref: thumb_outer_cluster
          shift: [-0.6px, -0.6py]
        - ref: matrix_ring_bottom
          shift: [0.8px, -0.6py]
        - ref: matrix_ring_bottom
          shift: [-0.22px, -0.6py]

        - ref: matrix_pinkie_bottom
          shift: [0.6px, -0.6py]
        - ref: matrix_pinkie_bottom
          shift: [-0.6px, -0.6py]

  mounting:
    - what: circle
      radius: 1standoff
      where:
        ref: [matrix_pinkie_top]
        shift: [11, 10]
    - what: circle
      radius: 1standoff
      where:
        ref: [matrix_middle_bottom]
        shift: [0, -0.8ky]
    - what: circle
      radius: 1standoff
      where:
        ref: [thumb_space_cluster]
        shift: [-0.3kx, -0.8ky]
    - what: circle
      radius: 1standoff
      where:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0kx, 0.3ky]
    - what: circle
      radius: 1standoff
      where:
        ref: [mirror_matrix_pinkie_top]
        shift: [11, 10]
    - what: circle
      radius: 1standoff
      where:
        ref: [mirror_matrix_middle_bottom]
        shift: [0, -0.8ky]
    - what: circle
      radius: 1standoff
      where:
        ref: [mirror_thumb_space_cluster]
        shift: [-0.3kx, -0.8ky]
  combo:
    - name: board
    - operation: subtract
      name: keys
    - operation: subtract
      name: mounting
pcbs:
  flexible-determinist:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      controller:
        what: feather_rp2040
        params:
          mounting: true
        where:
          ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [0,-1]
          rotate: 90
      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_pinkie_top]
          shift: [11, 10]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_middle_bottom]
          shift: [0, -0.8ky]
      hole_bottom_inner_left:
        what: mountinghole
        where:
          ref: [thumb_space_cluster]
          shift: [-0.3kx, -0.8ky]
      hole_center:
        what: mountinghole
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0kx, 0.3ky]
      hole_top_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinkie_top]
          shift: [11, 10]
      hole_bottom_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_bottom]
          shift: [0, -0.8ky]
      hole_bottom_inner_right:
        what: mountinghole
        where:
          ref: [mirror_thumb_space_cluster]
          shift: [-0.3kx, -0.8ky]
cases:
  _mounting:
    - name: mounting
      extrude: 4
  bottom:
    - name: board
      extrude: 2
  case:
    - what: case
      name: bottom
      operation: add
    - what: case
      name: _mounting
      operation: add